-- 1. CREACIÓN E INICIALIZACIÓN DE LA BASE DE DATOS
CREATE DATABASE IF NOT EXISTS TP_INTEGRACION;
USE TP_INTEGRACION;

-- 2. ELIMINACIÓN DE TABLAS PREVIAS (En orden inverso por las FK)
DROP TABLE IF EXISTS TBL_LINEA_DE_VENTA;
DROP TABLE IF EXISTS TBL_VENTA;
DROP TABLE IF EXISTS TBL_PRODUCTO;
DROP TABLE IF EXISTS TBL_USUARIO;

-- 3. CREACIÓN DE TABLAS MAESTRAS (No dependen de nadie)

-- Tabla: TBL_PRODUCTO
CREATE TABLE TBL_PRODUCTO (
    CODIGO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(100),
    STOCK INT,
    ACTIVO BIT,
    PRECIO DECIMAL(15,2),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO)
);

-- Tabla: TBL_VENTA
CREATE TABLE TBL_VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    FECHA DATETIME,
    CLIENTE VARCHAR(200),
    TOTAL DECIMAL(15,2),
    RECHAZADA BIT, -- 0 = válida, 1 = rechazada (Agregado del DER)
    CONSTRAINT PK_VENTA PRIMARY KEY (ID)
);

-- 4. CREACIÓN DE TABLAS DEPENDIENTES (Dependen de Producto y Venta)

-- Tabla: TBL_LINEA_DE_VENTA
CREATE TABLE TBL_LINEA_DE_VENTA (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_VENTA INT NOT NULL,
    CODIGO_PRODUCTO VARCHAR(20) NOT NULL,
    CANTIDAD INT, 
    PRECIO_UNITARIO DECIMAL(15,2),
    SUBTOTAL DECIMAL(15,2),
    CONSTRAINT PK_LINEA_DE_VENTA PRIMARY KEY (ID),
    CONSTRAINT FK_LDV_VENTA FOREIGN KEY (ID_VENTA) REFERENCES TBL_VENTA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LDV_PRODUCTO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES TBL_PRODUCTO(CODIGO)
);

-- 5. CREACIÓN DE TABLA DE USUARIOS (Para autenticación y autorización)

-- Tabla: TBL_USUARIO
CREATE TABLE TBL_USUARIO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(255),
    ROL VARCHAR(50),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);

-- 5. VERIFICACIÓN OPERATIVA
SELECT 'Tablas creadas con éxito' AS ESTADO;